export interface InsiderTransaction {
  id: string;
  ticker: string;
  companyName: string;
  insiderName: string;
  insiderTitle: string;
  transactionType: "alım" | "satım";
  shares: number;
  pricePerShare: number;
  totalValue: number;
  transactionDate: string;
  announcementDate: string;
  ownershipAfter: number;
  relation: "yönetici" | "ortak" | "aile";
}

export const MOCK_INSIDER_TRANSACTIONS: InsiderTransaction[] = [
  {
    id: "ins-001",
    ticker: "THYAO",
    companyName: "Türk Hava Yolları A.O.",
    insiderName: "Ahmet Bolat",
    insiderTitle: "Yönetim Kurulu Başkanı",
    transactionType: "alım",
    shares: 250_000,
    pricePerShare: 312.40,
    totalValue: 78_100_000,
    transactionDate: "2026-04-02",
    announcementDate: "2026-04-03",
    ownershipAfter: 0.18,
    relation: "yönetici",
  },
  {
    id: "ins-002",
    ticker: "GARAN",
    companyName: "Garanti BBVA Bankası A.Ş.",
    insiderName: "Recep Baştuğ",
    insiderTitle: "Genel Müdür",
    transactionType: "alım",
    shares: 180_000,
    pricePerShare: 142.60,
    totalValue: 25_668_000,
    transactionDate: "2026-04-03",
    announcementDate: "2026-04-04",
    ownershipAfter: 0.07,
    relation: "yönetici",
  },
  {
    id: "ins-003",
    ticker: "ASELS",
    companyName: "Aselsan Elektronik San. ve Tic. A.Ş.",
    insiderName: "Haluk Görgün",
    insiderTitle: "Yönetim Kurulu Başkanı",
    transactionType: "alım",
    shares: 120_000,
    pricePerShare: 98.50,
    totalValue: 11_820_000,
    transactionDate: "2026-04-04",
    announcementDate: "2026-04-04",
    ownershipAfter: 0.05,
    relation: "yönetici",
  },
  {
    id: "ins-004",
    ticker: "KCHOL",
    companyName: "Koç Holding A.Ş.",
    insiderName: "Levent Çakıroğlu",
    insiderTitle: "Genel Müdür",
    transactionType: "satım",
    shares: 95_000,
    pricePerShare: 218.30,
    totalValue: 20_738_500,
    transactionDate: "2026-04-04",
    announcementDate: "2026-04-05",
    ownershipAfter: 0.12,
    relation: "yönetici",
  },
  {
    id: "ins-005",
    ticker: "SAHOL",
    companyName: "Sabancı Holding A.Ş.",
    insiderName: "Cenk Alper",
    insiderTitle: "Genel Müdür",
    transactionType: "alım",
    shares: 200_000,
    pricePerShare: 86.20,
    totalValue: 17_240_000,
    transactionDate: "2026-04-05",
    announcementDate: "2026-04-06",
    ownershipAfter: 0.09,
    relation: "yönetici",
  },
  {
    id: "ins-006",
    ticker: "BIMAS",
    companyName: "BİM Birleşik Mağazalar A.Ş.",
    insiderName: "Galip Aykaç",
    insiderTitle: "Yönetim Kurulu Üyesi",
    transactionType: "satım",
    shares: 40_000,
    pricePerShare: 540.00,
    totalValue: 21_600_000,
    transactionDate: "2026-04-05",
    announcementDate: "2026-04-06",
    ownershipAfter: 1.85,
    relation: "ortak",
  },
  {
    id: "ins-007",
    ticker: "TUPRS",
    companyName: "Tüpraş Türkiye Petrol Rafinerileri A.Ş.",
    insiderName: "İbrahim Yelmenoğlu",
    insiderTitle: "Genel Müdür",
    transactionType: "alım",
    shares: 60_000,
    pricePerShare: 185.70,
    totalValue: 11_142_000,
    transactionDate: "2026-04-07",
    announcementDate: "2026-04-07",
    ownershipAfter: 0.04,
    relation: "yönetici",
  },
  {
    id: "ins-008",
    ticker: "SISE",
    companyName: "Türkiye Şişe ve Cam Fabrikaları A.Ş.",
    insiderName: "Görkem Elverici",
    insiderTitle: "Yönetim Kurulu Üyesi",
    transactionType: "satım",
    shares: 150_000,
    pricePerShare: 54.80,
    totalValue: 8_220_000,
    transactionDate: "2026-04-07",
    announcementDate: "2026-04-08",
    ownershipAfter: 0.32,
    relation: "yönetici",
  },
  {
    id: "ins-009",
    ticker: "EREGL",
    companyName: "Ereğli Demir ve Çelik Fabrikaları A.Ş.",
    insiderName: "Veysel Yayan",
    insiderTitle: "Bağımsız Yönetim Kurulu Üyesi",
    transactionType: "alım",
    shares: 300_000,
    pricePerShare: 62.30,
    totalValue: 18_690_000,
    transactionDate: "2026-04-08",
    announcementDate: "2026-04-08",
    ownershipAfter: 0.11,
    relation: "yönetici",
  },
  {
    id: "ins-010",
    ticker: "FROTO",
    companyName: "Ford Otomotiv Sanayi A.Ş.",
    insiderName: "Haydar Yenigün",
    insiderTitle: "Genel Müdür",
    transactionType: "alım",
    shares: 25_000,
    pricePerShare: 1_120.00,
    totalValue: 28_000_000,
    transactionDate: "2026-04-08",
    announcementDate: "2026-04-09",
    ownershipAfter: 0.06,
    relation: "yönetici",
  },
  {
    id: "ins-011",
    ticker: "TOASO",
    companyName: "Tofaş Türk Otomobil Fabrikası A.Ş.",
    insiderName: "Cengiz Eroldu",
    insiderTitle: "Genel Müdür",
    transactionType: "satım",
    shares: 70_000,
    pricePerShare: 310.50,
    totalValue: 21_735_000,
    transactionDate: "2026-04-09",
    announcementDate: "2026-04-09",
    ownershipAfter: 0.15,
    relation: "yönetici",
  },
  {
    id: "ins-012",
    ticker: "THYAO",
    companyName: "Türk Hava Yolları A.O.",
    insiderName: "Bilal Ekşi",
    insiderTitle: "Genel Müdür Yardımcısı",
    transactionType: "alım",
    shares: 100_000,
    pricePerShare: 318.20,
    totalValue: 31_820_000,
    transactionDate: "2026-04-09",
    announcementDate: "2026-04-10",
    ownershipAfter: 0.06,
    relation: "yönetici",
  },
  {
    id: "ins-013",
    ticker: "GARAN",
    companyName: "Garanti BBVA Bankası A.Ş.",
    insiderName: "Ebru Dildar Edin",
    insiderTitle: "Yönetim Kurulu Üyesi",
    transactionType: "alım",
    shares: 90_000,
    pricePerShare: 145.30,
    totalValue: 13_077_000,
    transactionDate: "2026-04-10",
    announcementDate: "2026-04-10",
    ownershipAfter: 0.03,
    relation: "yönetici",
  },
  {
    id: "ins-014",
    ticker: "AKBNK",
    companyName: "Akbank T.A.Ş.",
    insiderName: "Hakan Binbaşgil",
    insiderTitle: "Genel Müdür",
    transactionType: "satım",
    shares: 110_000,
    pricePerShare: 68.40,
    totalValue: 7_524_000,
    transactionDate: "2026-04-10",
    announcementDate: "2026-04-11",
    ownershipAfter: 0.08,
    relation: "yönetici",
  },
  {
    id: "ins-015",
    ticker: "TCELL",
    companyName: "Turkcell İletişim Hizmetleri A.Ş.",
    insiderName: "Ali Taha Koç",
    insiderTitle: "Yönetim Kurulu Başkanı",
    transactionType: "alım",
    shares: 160_000,
    pricePerShare: 92.10,
    totalValue: 14_736_000,
    transactionDate: "2026-04-11",
    announcementDate: "2026-04-11",
    ownershipAfter: 0.10,
    relation: "yönetici",
  },
  {
    id: "ins-016",
    ticker: "THYAO",
    companyName: "Türk Hava Yolları A.O.",
    insiderName: "Fatma Bolat",
    insiderTitle: "Yönetim Kurulu Başkanı Eşi",
    transactionType: "alım",
    shares: 50_000,
    pricePerShare: 320.00,
    totalValue: 16_000_000,
    transactionDate: "2026-04-11",
    announcementDate: "2026-04-12",
    ownershipAfter: 0.03,
    relation: "aile",
  },
  {
    id: "ins-017",
    ticker: "PGSUS",
    companyName: "Pegasus Hava Taşımacılığı A.Ş.",
    insiderName: "Mehmet Nane",
    insiderTitle: "Genel Müdür",
    transactionType: "satım",
    shares: 35_000,
    pricePerShare: 870.00,
    totalValue: 30_450_000,
    transactionDate: "2026-04-11",
    announcementDate: "2026-04-12",
    ownershipAfter: 0.22,
    relation: "yönetici",
  },
  {
    id: "ins-018",
    ticker: "KOZAL",
    companyName: "Koza Altın İşletmeleri A.Ş.",
    insiderName: "İpek Koza",
    insiderTitle: "Yönetim Kurulu Üyesi",
    transactionType: "alım",
    shares: 80_000,
    pricePerShare: 156.80,
    totalValue: 12_544_000,
    transactionDate: "2026-04-12",
    announcementDate: "2026-04-12",
    ownershipAfter: 0.45,
    relation: "ortak",
  },
  {
    id: "ins-019",
    ticker: "ASELS",
    companyName: "Aselsan Elektronik San. ve Tic. A.Ş.",
    insiderName: "Murat Ercan",
    insiderTitle: "Genel Müdür Yardımcısı",
    transactionType: "alım",
    shares: 75_000,
    pricePerShare: 99.80,
    totalValue: 7_485_000,
    transactionDate: "2026-04-12",
    announcementDate: "2026-04-13",
    ownershipAfter: 0.02,
    relation: "yönetici",
  },
  {
    id: "ins-020",
    ticker: "YKBNK",
    companyName: "Yapı ve Kredi Bankası A.Ş.",
    insiderName: "Erhan Adalı",
    insiderTitle: "Genel Müdür",
    transactionType: "alım",
    shares: 140_000,
    pricePerShare: 38.50,
    totalValue: 5_390_000,
    transactionDate: "2026-04-13",
    announcementDate: "2026-04-13",
    ownershipAfter: 0.04,
    relation: "yönetici",
  },
  {
    id: "ins-021",
    ticker: "ENKAI",
    companyName: "Enka İnşaat ve Sanayi A.Ş.",
    insiderName: "Sinan Tara",
    insiderTitle: "Yönetim Kurulu Başkanı",
    transactionType: "satım",
    shares: 200_000,
    pricePerShare: 45.20,
    totalValue: 9_040_000,
    transactionDate: "2026-04-13",
    announcementDate: "2026-04-14",
    ownershipAfter: 2.10,
    relation: "ortak",
  },
  {
    id: "ins-022",
    ticker: "FROTO",
    companyName: "Ford Otomotiv Sanayi A.Ş.",
    insiderName: "Özgür Yücetürk",
    insiderTitle: "Mali İşler Direktörü",
    transactionType: "satım",
    shares: 15_000,
    pricePerShare: 1_135.00,
    totalValue: 17_025_000,
    transactionDate: "2026-04-14",
    announcementDate: "2026-04-14",
    ownershipAfter: 0.02,
    relation: "yönetici",
  },
  {
    id: "ins-023",
    ticker: "EREGL",
    companyName: "Ereğli Demir ve Çelik Fabrikaları A.Ş.",
    insiderName: "Başar Yıldırım",
    insiderTitle: "Yönetim Kurulu Üyesi",
    transactionType: "alım",
    shares: 450_000,
    pricePerShare: 63.10,
    totalValue: 28_395_000,
    transactionDate: "2026-04-14",
    announcementDate: "2026-04-14",
    ownershipAfter: 0.25,
    relation: "ortak",
  },
  {
    id: "ins-024",
    ticker: "SAHOL",
    companyName: "Sabancı Holding A.Ş.",
    insiderName: "Güler Sabancı",
    insiderTitle: "Yönetim Kurulu Başkanı",
    transactionType: "alım",
    shares: 500_000,
    pricePerShare: 87.40,
    totalValue: 43_700_000,
    transactionDate: "2026-04-14",
    announcementDate: "2026-04-14",
    ownershipAfter: 3.45,
    relation: "ortak",
  },
  {
    id: "ins-025",
    ticker: "TUPRS",
    companyName: "Tüpraş Türkiye Petrol Rafinerileri A.Ş.",
    insiderName: "Ziya Erdem",
    insiderTitle: "Yönetim Kurulu Üyesi",
    transactionType: "satım",
    shares: 30_000,
    pricePerShare: 188.50,
    totalValue: 5_655_000,
    transactionDate: "2026-04-14",
    announcementDate: "2026-04-14",
    ownershipAfter: 0.08,
    relation: "yönetici",
  },
];
