// Mock economic calendar data for BistWall

export type EventImportance = "yüksek" | "orta" | "düşük";
export type EventCategory =
  | "faiz"
  | "enflasyon"
  | "büyüme"
  | "istihdam"
  | "dış_ticaret"
  | "sanayi"
  | "güven"
  | "diğer";

export interface EconomicEvent {
  id: string;
  date: string; // ISO date
  time: string; // "14:00" or "\u2014" if no specific time
  title: string; // "TCMB Faiz Kararı"
  category: EventCategory;
  importance: EventImportance;
  source: string; // "TCMB", "TÜİK", "Hazine", etc.
  previous: string; // "50.00%", "67.07%", etc.
  forecast: string | null; // consensus forecast
  actual: string | null; // actual value (null if not yet released)
  impact: string; // short explanation
  affectedSectors: string[]; // ["Bankacılık", "Holding"]
}

export const EVENT_CATEGORY_LABELS: Record<EventCategory, string> = {
  faiz: "Faiz",
  enflasyon: "Enflasyon",
  büyüme: "Büyüme",
  istihdam: "İstihdam",
  dış_ticaret: "Dış Ticaret",
  sanayi: "Sanayi",
  güven: "Güven",
  diğer: "Diğer",
};

export const MOCK_ECONOMIC_EVENTS: EconomicEvent[] = [
  // ── April 2026 ──
  {
    id: "ec-001",
    date: "2026-04-03",
    time: "10:00",
    title: "TÜFE (Mart - Yıllık)",
    category: "enflasyon",
    importance: "yüksek",
    source: "TÜİK",
    previous: "%36.08",
    forecast: "%34.50",
    actual: "%34.82",
    impact: "Enflasyon beklentilerin hafif üzerinde, TL üzerinde baskı oluşturabilir",
    affectedSectors: ["Bankacılık", "Perakende", "GYO"],
  },
  {
    id: "ec-002",
    date: "2026-04-03",
    time: "10:00",
    title: "ÜFE (Mart - Yıllık)",
    category: "enflasyon",
    importance: "orta",
    source: "TÜİK",
    previous: "%27.63",
    forecast: "%26.80",
    actual: "%27.15",
    impact: "Üretici fiyatları yavaşlama eğiliminde, maliyet baskısı azalıyor",
    affectedSectors: ["Sanayi", "Gıda", "Otomotiv"],
  },
  {
    id: "ec-003",
    date: "2026-04-07",
    time: "10:00",
    title: "Perakende Satışlar (Şubat)",
    category: "büyüme",
    importance: "orta",
    source: "TÜİK",
    previous: "%16.2",
    forecast: "%14.8",
    actual: "%15.1",
    impact: "İç talep güçlü seyretmeye devam ediyor",
    affectedSectors: ["Perakende", "Gıda", "Teknoloji"],
  },
  {
    id: "ec-004",
    date: "2026-04-08",
    time: "10:00",
    title: "Sanayi Üretimi (Şubat)",
    category: "sanayi",
    importance: "orta",
    source: "TÜİK",
    previous: "%2.1",
    forecast: "%2.5",
    actual: "%2.8",
    impact: "Sanayi üretiminde toparlanma sinyalleri güçleniyor",
    affectedSectors: ["Sanayi", "Otomotiv", "Demir-Çelik"],
  },
  {
    id: "ec-005",
    date: "2026-04-10",
    time: "10:00",
    title: "İşsizlik Oranı (Şubat)",
    category: "istihdam",
    importance: "orta",
    source: "TÜİK",
    previous: "%8.7",
    forecast: "%8.5",
    actual: "%8.6",
    impact: "İstihdam piyasası istikrarlı seyrediyor",
    affectedSectors: ["Perakende", "İnşaat", "Hizmet"],
  },
  {
    id: "ec-006",
    date: "2026-04-11",
    time: "10:00",
    title: "Cari Denge (Şubat)",
    category: "dış_ticaret",
    importance: "orta",
    source: "TCMB",
    previous: "-1.82 mlr $",
    forecast: "-2.10 mlr $",
    actual: "-1.95 mlr $",
    impact: "Cari açık beklentilerden iyi, dış denge iyileşiyor",
    affectedSectors: ["Bankacılık", "Enerji", "Havacılık"],
  },
  {
    id: "ec-007",
    date: "2026-04-14",
    time: "14:00",
    title: "Tüketici Güven Endeksi (Nisan)",
    category: "güven",
    importance: "düşük",
    source: "TÜİK",
    previous: "82.4",
    forecast: "83.0",
    actual: null,
    impact: "Tüketici güveni iç talep ve perakende sektörü için öncü gösterge",
    affectedSectors: ["Perakende", "Otomotiv", "GYO"],
  },
  {
    id: "ec-008",
    date: "2026-04-15",
    time: "10:00",
    title: "Konut Satışları (Mart)",
    category: "diğer",
    importance: "düşük",
    source: "TÜİK",
    previous: "98,432",
    forecast: "105,000",
    actual: null,
    impact: "Konut piyasası hareketliliği GYO ve bankacılık için önemli",
    affectedSectors: ["GYO", "Bankacılık", "İnşaat", "Çimento"],
  },
  {
    id: "ec-009",
    date: "2026-04-17",
    time: "14:00",
    title: "TCMB Faiz Kararı (Nisan)",
    category: "faiz",
    importance: "yüksek",
    source: "TCMB",
    previous: "%42.50",
    forecast: "%42.50",
    actual: null,
    impact: "TL ve borsa için kritik karar, piyasa faiz indirimi bekliyor",
    affectedSectors: ["Bankacılık", "Holding", "GYO", "Sigorta"],
  },
  {
    id: "ec-010",
    date: "2026-04-20",
    time: "10:00",
    title: "Bütçe Dengesi (Mart)",
    category: "diğer",
    importance: "düşük",
    source: "Hazine",
    previous: "-78.2 mlr TL",
    forecast: "-65.0 mlr TL",
    actual: null,
    impact: "Mali disiplin göstergesi, CDS primi üzerinde etkili",
    affectedSectors: ["Bankacılık", "Holding"],
  },
  {
    id: "ec-011",
    date: "2026-04-22",
    time: "10:00",
    title: "Dış Ticaret Dengesi (Mart)",
    category: "dış_ticaret",
    importance: "orta",
    source: "TÜİK",
    previous: "-5.12 mlr $",
    forecast: "-4.80 mlr $",
    actual: null,
    impact: "İhracat performansı ve ithalat bağımlılığı TL üzerinde etkili",
    affectedSectors: ["Otomotiv", "Tekstil", "Demir-Çelik", "Havacılık"],
  },
  {
    id: "ec-012",
    date: "2026-04-24",
    time: "10:00",
    title: "Kapasite Kullanım Oranı (Nisan)",
    category: "sanayi",
    importance: "düşük",
    source: "TCMB",
    previous: "%76.8",
    forecast: "%77.2",
    actual: null,
    impact: "Sanayi sektörünün üretim gücünü yansıtır",
    affectedSectors: ["Sanayi", "Otomotiv"],
  },
  {
    id: "ec-013",
    date: "2026-04-28",
    time: "10:00",
    title: "Turizm Gelirleri (Q1 2026)",
    category: "dış_ticaret",
    importance: "orta",
    source: "TÜİK",
    previous: "8.45 mlr $",
    forecast: "9.20 mlr $",
    actual: null,
    impact: "Turizm gelirleri cari dengeyi destekleyen en önemli kalem",
    affectedSectors: ["Havacılık", "Turizm", "Perakende"],
  },
  {
    id: "ec-014",
    date: "2026-04-30",
    time: "10:00",
    title: "Otomobil Satışları (Nisan)",
    category: "sanayi",
    importance: "düşük",
    source: "ODD",
    previous: "72,450",
    forecast: "68,000",
    actual: null,
    impact: "İç talep ve tüketici harcama eğiliminin göstergesi",
    affectedSectors: ["Otomotiv", "Bankacılık", "Sigorta"],
  },
  // ── May 2026 ──
  {
    id: "ec-015",
    date: "2026-05-05",
    time: "10:00",
    title: "TÜFE (Nisan - Yıllık)",
    category: "enflasyon",
    importance: "yüksek",
    source: "TÜİK",
    previous: "%34.82",
    forecast: "%33.10",
    actual: null,
    impact: "Dezenflasyon sürecinin devamı piyasalar için olumlu sinyal",
    affectedSectors: ["Bankacılık", "Perakende", "GYO"],
  },
  {
    id: "ec-016",
    date: "2026-05-05",
    time: "10:00",
    title: "ÜFE (Nisan - Yıllık)",
    category: "enflasyon",
    importance: "orta",
    source: "TÜİK",
    previous: "%27.15",
    forecast: "%25.90",
    actual: null,
    impact: "Üretici fiyatlarındaki düşüş marjları destekler",
    affectedSectors: ["Sanayi", "Gıda", "Otomotiv"],
  },
  {
    id: "ec-017",
    date: "2026-05-08",
    time: "10:00",
    title: "Sanayi Üretimi (Mart)",
    category: "sanayi",
    importance: "orta",
    source: "TÜİK",
    previous: "%2.8",
    forecast: "%3.0",
    actual: null,
    impact: "İmalat sektöründeki ivme GSYİH büyümesini destekler",
    affectedSectors: ["Sanayi", "Otomotiv", "Demir-Çelik"],
  },
  {
    id: "ec-018",
    date: "2026-05-12",
    time: "10:00",
    title: "İşsizlik Oranı (Mart)",
    category: "istihdam",
    importance: "orta",
    source: "TÜİK",
    previous: "%8.6",
    forecast: "%8.4",
    actual: null,
    impact: "İstihdam artışı iç talebi ve tüketimi destekler",
    affectedSectors: ["Perakende", "İnşaat", "Hizmet"],
  },
  {
    id: "ec-019",
    date: "2026-05-13",
    time: "10:00",
    title: "Cari Denge (Mart)",
    category: "dış_ticaret",
    importance: "orta",
    source: "TCMB",
    previous: "-1.95 mlr $",
    forecast: "-2.30 mlr $",
    actual: null,
    impact: "Cari açığın seyri TL ve faiz beklentileri için belirleyici",
    affectedSectors: ["Bankacılık", "Enerji", "Havacılık"],
  },
  {
    id: "ec-020",
    date: "2026-05-15",
    time: "10:00",
    title: "GSYİH Büyüme (Q1 2026 - Öncü)",
    category: "büyüme",
    importance: "yüksek",
    source: "TÜİK",
    previous: "%3.2",
    forecast: "%3.5",
    actual: null,
    impact: "Ekonomik büyüme hızı tüm sektörleri etkileyen temel gösterge",
    affectedSectors: ["Bankacılık", "Holding", "Sanayi", "Perakende"],
  },
  {
    id: "ec-021",
    date: "2026-05-18",
    time: "14:00",
    title: "Tüketici Güven Endeksi (Mayıs)",
    category: "güven",
    importance: "düşük",
    source: "TÜİK",
    previous: "83.0",
    forecast: "84.5",
    actual: null,
    impact: "Güven endeksindeki yükseliş tüketim harcamalarını destekler",
    affectedSectors: ["Perakende", "Otomotiv", "GYO"],
  },
  {
    id: "ec-022",
    date: "2026-05-22",
    time: "14:00",
    title: "TCMB Faiz Kararı (Mayıs)",
    category: "faiz",
    importance: "yüksek",
    source: "TCMB",
    previous: "%42.50",
    forecast: "%40.00",
    actual: null,
    impact: "Faiz indirimi beklentisi güçlü, 250 baz puan indirim fiyatlanıyor",
    affectedSectors: ["Bankacılık", "Holding", "GYO", "Sigorta"],
  },
  {
    id: "ec-023",
    date: "2026-05-25",
    time: "10:00",
    title: "Dış Ticaret Dengesi (Nisan)",
    category: "dış_ticaret",
    importance: "orta",
    source: "TÜİK",
    previous: "-4.80 mlr $",
    forecast: "-5.10 mlr $",
    actual: null,
    impact: "İhracatta mevsimsel toparlanma bekleniyor",
    affectedSectors: ["Otomotiv", "Tekstil", "Demir-Çelik"],
  },
  {
    id: "ec-024",
    date: "2026-05-27",
    time: "10:00",
    title: "PMI İmalat (Mayıs)",
    category: "sanayi",
    importance: "orta",
    source: "İstanbul Sanayi Odası",
    previous: "51.2",
    forecast: "51.8",
    actual: null,
    impact: "50 üzeri genişlemeye işaret, imalat sektörü toparlanıyor",
    affectedSectors: ["Sanayi", "Otomotiv", "Demir-Çelik"],
  },
  // ── June 2026 ──
  {
    id: "ec-025",
    date: "2026-06-03",
    time: "10:00",
    title: "TÜFE (Mayıs - Yıllık)",
    category: "enflasyon",
    importance: "yüksek",
    source: "TÜİK",
    previous: "%33.10",
    forecast: "%31.50",
    actual: null,
    impact: "Enflasyonda düşüş trendi sürdükçe faiz indirimi alanı açılır",
    affectedSectors: ["Bankacılık", "Perakende", "GYO"],
  },
  {
    id: "ec-026",
    date: "2026-06-03",
    time: "10:00",
    title: "ÜFE (Mayıs - Yıllık)",
    category: "enflasyon",
    importance: "orta",
    source: "TÜİK",
    previous: "%25.90",
    forecast: "%24.60",
    actual: null,
    impact: "Üretici fiyat artışı yavaşlıyor, şirket marjları genişleyebilir",
    affectedSectors: ["Sanayi", "Gıda", "Otomotiv"],
  },
  {
    id: "ec-027",
    date: "2026-06-10",
    time: "10:00",
    title: "İşsizlik Oranı (Nisan)",
    category: "istihdam",
    importance: "orta",
    source: "TÜİK",
    previous: "%8.4",
    forecast: "%8.3",
    actual: null,
    impact: "İstihdam piyasasında iyileşme trendi devam ediyor",
    affectedSectors: ["Perakende", "İnşaat", "Hizmet"],
  },
  {
    id: "ec-028",
    date: "2026-06-19",
    time: "14:00",
    title: "TCMB Faiz Kararı (Haziran)",
    category: "faiz",
    importance: "yüksek",
    source: "TCMB",
    previous: "%40.00",
    forecast: "%37.50",
    actual: null,
    impact: "Agresif indirim döngüsü devam ederse borsa rallisi sürebilir",
    affectedSectors: ["Bankacılık", "Holding", "GYO", "Sigorta"],
  },
  {
    id: "ec-029",
    date: "2026-06-22",
    time: "10:00",
    title: "Turizm Gelirleri (Nisan)",
    category: "dış_ticaret",
    importance: "orta",
    source: "TÜİK",
    previous: "9.20 mlr $",
    forecast: "5.80 mlr $",
    actual: null,
    impact: "Yaz sezonu öncesi turizm gelirlerinde artış bekleniyor",
    affectedSectors: ["Havacılık", "Turizm", "Perakende"],
  },
  {
    id: "ec-030",
    date: "2026-06-26",
    time: "10:00",
    title: "Reel Efektif Döviz Kuru (Mayıs)",
    category: "diğer",
    importance: "düşük",
    source: "TCMB",
    previous: "72.4",
    forecast: "73.0",
    actual: null,
    impact: "TL'nin reel değeri ihracat rekabetçiliğini etkiler",
    affectedSectors: ["Otomotiv", "Tekstil", "Havacılık"],
  },
];

// Impact matrix: which categories affect which sectors
export const IMPACT_MATRIX: Record<
  EventCategory,
  Record<string, "yüksek" | "orta" | "düşük">
> = {
  faiz: {
    Bankacılık: "yüksek",
    Holding: "yüksek",
    GYO: "yüksek",
    Sigorta: "orta",
    Sanayi: "orta",
    Perakende: "orta",
    Otomotiv: "düşük",
  },
  enflasyon: {
    Bankacılık: "yüksek",
    Perakende: "yüksek",
    GYO: "orta",
    Sanayi: "orta",
    Gıda: "yüksek",
    Otomotiv: "orta",
    Holding: "düşük",
  },
  büyüme: {
    Bankacılık: "yüksek",
    Holding: "yüksek",
    Sanayi: "yüksek",
    Perakende: "orta",
    GYO: "orta",
    Otomotiv: "orta",
    Sigorta: "düşük",
  },
  istihdam: {
    Perakende: "yüksek",
    İnşaat: "yüksek",
    Sanayi: "orta",
    Bankacılık: "düşük",
    Otomotiv: "düşük",
    GYO: "orta",
    Holding: "düşük",
  },
  dış_ticaret: {
    Otomotiv: "yüksek",
    Havacılık: "yüksek",
    Tekstil: "yüksek",
    "Demir-Çelik": "orta",
    Bankacılık: "orta",
    Enerji: "orta",
    Perakende: "düşük",
  },
  sanayi: {
    Sanayi: "yüksek",
    Otomotiv: "yüksek",
    "Demir-Çelik": "yüksek",
    Enerji: "orta",
    Bankacılık: "düşük",
    Holding: "düşük",
    Perakende: "düşük",
  },
  güven: {
    Perakende: "yüksek",
    Otomotiv: "orta",
    GYO: "orta",
    Bankacılık: "düşük",
    Sanayi: "düşük",
    Holding: "düşük",
    Sigorta: "düşük",
  },
  diğer: {
    Bankacılık: "orta",
    GYO: "orta",
    Holding: "düşük",
    Sanayi: "düşük",
    Otomotiv: "düşük",
    Perakende: "düşük",
    Havacılık: "düşük",
  },
};
