// TEFAS Fund Analysis Mock Data

export type FundType =
  | "Hisse Senedi"
  | "Borçlanma Araçları"
  | "Karma"
  | "Para Piyasası"
  | "Altın"
  | "Katılım"
  | "Fon Sepeti"
  | "Değişken";

export interface TefasFund {
  code: string;
  name: string;
  manager: string;
  type: FundType;
  price: number;
  returnDaily: number;
  returnWeekly: number;
  returnMonthly: number;
  returnYtd: number;
  return1y: number;
  return3y: number;
  aum: number;
  investorCount: number;
  managementFee: number;
  riskLevel: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  sharpeRatio: number;
  volatility: number;
  maxDrawdown: number;
  composition: { label: string; weight: number }[];
  topHoldings?: { ticker: string; weight: number }[];
  strategyFit: {
    conservative: number;
    balanced: number;
    growth: number;
    aggressive: number;
  };
}

export interface PortfolioRecommendation {
  strategy: string;
  description: string;
  riskLevel: string;
  expectedReturn: string;
  allocations: {
    fundCode: string;
    fundName: string;
    weight: number;
    reason: string;
  }[];
  warnings: string[];
}

export const MOCK_TEFAS_FUNDS: TefasFund[] = [
  // ── Hisse Senedi Fonları ──
  {
    code: "TI2",
    name: "İş Portföy BIST 30 Endeksi Hisse Senedi Fonu",
    manager: "İş Portföy",
    type: "Hisse Senedi",
    price: 3.847,
    returnDaily: 1.12,
    returnWeekly: 2.85,
    returnMonthly: 5.42,
    returnYtd: 18.7,
    return1y: 42.3,
    return3y: 185.6,
    aum: 12_450_000_000,
    investorCount: 284_500,
    managementFee: 1.09,
    riskLevel: 6,
    sharpeRatio: 1.24,
    volatility: 28.4,
    maxDrawdown: -18.6,
    composition: [
      { label: "Hisse Senedi", weight: 96.2 },
      { label: "Nakit", weight: 3.8 },
    ],
    topHoldings: [
      { ticker: "THYAO", weight: 12.8 },
      { ticker: "GARAN", weight: 10.2 },
      { ticker: "ASELS", weight: 8.7 },
      { ticker: "KCHOL", weight: 7.5 },
      { ticker: "AKBNK", weight: 6.9 },
    ],
    strategyFit: { conservative: 10, balanced: 45, growth: 80, aggressive: 95 },
  },
  {
    code: "IPB",
    name: "İş Portföy Hisse Senedi Fonu",
    manager: "İş Portföy",
    type: "Hisse Senedi",
    price: 5.214,
    returnDaily: 0.87,
    returnWeekly: 2.14,
    returnMonthly: 4.85,
    returnYtd: 22.4,
    return1y: 48.9,
    return3y: 210.3,
    aum: 8_920_000_000,
    investorCount: 195_200,
    managementFee: 1.52,
    riskLevel: 6,
    sharpeRatio: 1.38,
    volatility: 26.8,
    maxDrawdown: -16.2,
    composition: [
      { label: "Hisse Senedi", weight: 94.5 },
      { label: "Nakit", weight: 5.5 },
    ],
    topHoldings: [
      { ticker: "THYAO", weight: 9.8 },
      { ticker: "SAHOL", weight: 8.4 },
      { ticker: "GARAN", weight: 7.6 },
      { ticker: "BIMAS", weight: 6.2 },
      { ticker: "SISE", weight: 5.8 },
    ],
    strategyFit: { conservative: 8, balanced: 42, growth: 85, aggressive: 92 },
  },
  {
    code: "AK2",
    name: "Ak Portföy BIST 30 Endeksi Hisse Senedi Fonu",
    manager: "Ak Portföy",
    type: "Hisse Senedi",
    price: 2.956,
    returnDaily: 1.05,
    returnWeekly: 2.72,
    returnMonthly: 5.18,
    returnYtd: 17.9,
    return1y: 40.8,
    return3y: 178.2,
    aum: 6_780_000_000,
    investorCount: 162_300,
    managementFee: 1.15,
    riskLevel: 6,
    sharpeRatio: 1.18,
    volatility: 29.1,
    maxDrawdown: -19.4,
    composition: [
      { label: "Hisse Senedi", weight: 97.1 },
      { label: "Nakit", weight: 2.9 },
    ],
    topHoldings: [
      { ticker: "THYAO", weight: 13.1 },
      { ticker: "GARAN", weight: 10.5 },
      { ticker: "ASELS", weight: 9.0 },
      { ticker: "KCHOL", weight: 7.8 },
      { ticker: "YKBNK", weight: 6.4 },
    ],
    strategyFit: { conservative: 10, balanced: 44, growth: 78, aggressive: 94 },
  },
  {
    code: "YAY",
    name: "Yapı Kredi Portföy BIST 100 Endeksi Hisse Senedi Fonu",
    manager: "Yapı Kredi Portföy",
    type: "Hisse Senedi",
    price: 1.824,
    returnDaily: 0.94,
    returnWeekly: 2.38,
    returnMonthly: 4.62,
    returnYtd: 15.3,
    return1y: 36.2,
    return3y: 162.5,
    aum: 4_250_000_000,
    investorCount: 98_700,
    managementFee: 1.22,
    riskLevel: 6,
    sharpeRatio: 1.08,
    volatility: 27.6,
    maxDrawdown: -20.1,
    composition: [
      { label: "Hisse Senedi", weight: 95.8 },
      { label: "Nakit", weight: 4.2 },
    ],
    topHoldings: [
      { ticker: "THYAO", weight: 11.2 },
      { ticker: "GARAN", weight: 9.4 },
      { ticker: "AKBNK", weight: 7.8 },
      { ticker: "ASELS", weight: 6.5 },
      { ticker: "EREGL", weight: 5.2 },
    ],
    strategyFit: { conservative: 12, balanced: 48, growth: 75, aggressive: 90 },
  },
  {
    code: "GAH",
    name: "Garanti Portföy Hisse Senedi Fonu",
    manager: "Garanti Portföy",
    type: "Hisse Senedi",
    price: 4.128,
    returnDaily: 0.76,
    returnWeekly: 1.92,
    returnMonthly: 4.15,
    returnYtd: 20.1,
    return1y: 45.6,
    return3y: 195.8,
    aum: 5_640_000_000,
    investorCount: 134_800,
    managementFee: 1.45,
    riskLevel: 5,
    sharpeRatio: 1.32,
    volatility: 25.2,
    maxDrawdown: -15.8,
    composition: [
      { label: "Hisse Senedi", weight: 92.4 },
      { label: "Nakit", weight: 7.6 },
    ],
    topHoldings: [
      { ticker: "GARAN", weight: 8.9 },
      { ticker: "THYAO", weight: 8.4 },
      { ticker: "BIMAS", weight: 7.1 },
      { ticker: "TOASO", weight: 6.3 },
      { ticker: "TUPRS", weight: 5.7 },
    ],
    strategyFit: { conservative: 12, balanced: 50, growth: 82, aggressive: 88 },
  },
  {
    code: "TTE",
    name: "TEB Portföy Hisse Senedi Fonu",
    manager: "TEB Portföy",
    type: "Hisse Senedi",
    price: 2.385,
    returnDaily: 0.68,
    returnWeekly: 1.74,
    returnMonthly: 3.92,
    returnYtd: 14.8,
    return1y: 34.5,
    return3y: 148.7,
    aum: 2_180_000_000,
    investorCount: 52_400,
    managementFee: 1.38,
    riskLevel: 5,
    sharpeRatio: 1.05,
    volatility: 26.4,
    maxDrawdown: -17.3,
    composition: [
      { label: "Hisse Senedi", weight: 91.8 },
      { label: "Borçlanma Araçları", weight: 4.2 },
      { label: "Nakit", weight: 4.0 },
    ],
    topHoldings: [
      { ticker: "THYAO", weight: 10.4 },
      { ticker: "AKBNK", weight: 8.2 },
      { ticker: "GARAN", weight: 7.5 },
      { ticker: "EREGL", weight: 5.9 },
      { ticker: "SAHOL", weight: 5.1 },
    ],
    strategyFit: { conservative: 15, balanced: 46, growth: 76, aggressive: 86 },
  },

  // ── Borçlanma Araçları Fonları ──
  {
    code: "DZB",
    name: "Deniz Portföy Uzun Vadeli Borçlanma Araçları Fonu",
    manager: "Deniz Portföy",
    type: "Borçlanma Araçları",
    price: 1.452,
    returnDaily: 0.12,
    returnWeekly: 0.58,
    returnMonthly: 2.85,
    returnYtd: 12.4,
    return1y: 38.2,
    return3y: 142.6,
    aum: 3_890_000_000,
    investorCount: 78_600,
    managementFee: 0.72,
    riskLevel: 3,
    sharpeRatio: 1.82,
    volatility: 8.4,
    maxDrawdown: -4.2,
    composition: [
      { label: "Devlet Tahvili", weight: 52.8 },
      { label: "Özel Sektör Tahvili", weight: 34.6 },
      { label: "Nakit", weight: 12.6 },
    ],
    strategyFit: { conservative: 85, balanced: 70, growth: 35, aggressive: 15 },
  },
  {
    code: "AKK",
    name: "Ak Portföy Kısa Vadeli Borçlanma Araçları Fonu",
    manager: "Ak Portföy",
    type: "Borçlanma Araçları",
    price: 1.128,
    returnDaily: 0.14,
    returnWeekly: 0.65,
    returnMonthly: 3.12,
    returnYtd: 14.8,
    return1y: 42.5,
    return3y: 158.3,
    aum: 7_420_000_000,
    investorCount: 142_800,
    managementFee: 0.58,
    riskLevel: 2,
    sharpeRatio: 2.15,
    volatility: 5.2,
    maxDrawdown: -1.8,
    composition: [
      { label: "Kısa Vadeli Tahvil", weight: 48.5 },
      { label: "Bono", weight: 32.4 },
      { label: "Repo", weight: 14.1 },
      { label: "Nakit", weight: 5.0 },
    ],
    strategyFit: { conservative: 92, balanced: 65, growth: 25, aggressive: 8 },
  },
  {
    code: "IYB",
    name: "İş Portföy Yatırım Amaçlı Borçlanma Araçları Fonu",
    manager: "İş Portföy",
    type: "Borçlanma Araçları",
    price: 2.764,
    returnDaily: 0.11,
    returnWeekly: 0.52,
    returnMonthly: 2.64,
    returnYtd: 11.8,
    return1y: 36.4,
    return3y: 134.8,
    aum: 5_680_000_000,
    investorCount: 108_400,
    managementFee: 0.68,
    riskLevel: 3,
    sharpeRatio: 1.74,
    volatility: 9.1,
    maxDrawdown: -5.1,
    composition: [
      { label: "Devlet Tahvili", weight: 45.2 },
      { label: "Özel Sektör Tahvili", weight: 38.4 },
      { label: "Eurobond", weight: 10.2 },
      { label: "Nakit", weight: 6.2 },
    ],
    strategyFit: { conservative: 82, balanced: 68, growth: 32, aggressive: 12 },
  },

  // ── Altın Fonları ──
  {
    code: "GAL",
    name: "Garanti Portföy Altın Fonu",
    manager: "Garanti Portföy",
    type: "Altın",
    price: 6.482,
    returnDaily: 0.45,
    returnWeekly: 1.82,
    returnMonthly: 4.28,
    returnYtd: 24.6,
    return1y: 52.8,
    return3y: 245.2,
    aum: 9_850_000_000,
    investorCount: 312_400,
    managementFee: 0.85,
    riskLevel: 4,
    sharpeRatio: 1.56,
    volatility: 18.2,
    maxDrawdown: -12.4,
    composition: [
      { label: "Altın", weight: 92.8 },
      { label: "Nakit", weight: 7.2 },
    ],
    strategyFit: { conservative: 65, balanced: 60, growth: 45, aggressive: 30 },
  },
  {
    code: "IAL",
    name: "İş Portföy Altın Fonu",
    manager: "İş Portföy",
    type: "Altın",
    price: 5.918,
    returnDaily: 0.42,
    returnWeekly: 1.76,
    returnMonthly: 4.15,
    returnYtd: 23.8,
    return1y: 51.2,
    return3y: 238.6,
    aum: 11_240_000_000,
    investorCount: 425_800,
    managementFee: 0.78,
    riskLevel: 4,
    sharpeRatio: 1.52,
    volatility: 18.8,
    maxDrawdown: -13.1,
    composition: [
      { label: "Altın", weight: 94.2 },
      { label: "Nakit", weight: 5.8 },
    ],
    strategyFit: { conservative: 68, balanced: 62, growth: 48, aggressive: 32 },
  },

  // ── Karma Fonlar ──
  {
    code: "AKX",
    name: "Ak Portföy Karma Fon",
    manager: "Ak Portföy",
    type: "Karma",
    price: 2.384,
    returnDaily: 0.54,
    returnWeekly: 1.42,
    returnMonthly: 3.28,
    returnYtd: 14.2,
    return1y: 32.8,
    return3y: 128.4,
    aum: 3_420_000_000,
    investorCount: 86_200,
    managementFee: 1.18,
    riskLevel: 4,
    sharpeRatio: 1.28,
    volatility: 16.4,
    maxDrawdown: -10.8,
    composition: [
      { label: "Hisse Senedi", weight: 42.5 },
      { label: "Devlet Tahvili", weight: 28.4 },
      { label: "Özel Sektör Tahvili", weight: 15.8 },
      { label: "Nakit", weight: 13.3 },
    ],
    topHoldings: [
      { ticker: "GARAN", weight: 5.2 },
      { ticker: "THYAO", weight: 4.8 },
      { ticker: "AKBNK", weight: 3.9 },
    ],
    strategyFit: { conservative: 45, balanced: 85, growth: 55, aggressive: 30 },
  },
  {
    code: "IKA",
    name: "İş Portföy Karma Fon",
    manager: "İş Portföy",
    type: "Karma",
    price: 3.156,
    returnDaily: 0.48,
    returnWeekly: 1.28,
    returnMonthly: 3.05,
    returnYtd: 13.6,
    return1y: 30.4,
    return3y: 118.6,
    aum: 4_580_000_000,
    investorCount: 92_400,
    managementFee: 1.12,
    riskLevel: 4,
    sharpeRatio: 1.22,
    volatility: 15.8,
    maxDrawdown: -9.6,
    composition: [
      { label: "Hisse Senedi", weight: 38.2 },
      { label: "Devlet Tahvili", weight: 32.6 },
      { label: "Özel Sektör Tahvili", weight: 18.4 },
      { label: "Nakit", weight: 10.8 },
    ],
    topHoldings: [
      { ticker: "THYAO", weight: 4.5 },
      { ticker: "SAHOL", weight: 3.8 },
      { ticker: "KCHOL", weight: 3.2 },
    ],
    strategyFit: { conservative: 48, balanced: 88, growth: 52, aggressive: 28 },
  },

  // ── Para Piyasası Fonları ──
  {
    code: "IPL",
    name: "İş Portföy Para Piyasası Fonu",
    manager: "İş Portföy",
    type: "Para Piyasası",
    price: 1.048,
    returnDaily: 0.13,
    returnWeekly: 0.72,
    returnMonthly: 3.42,
    returnYtd: 16.2,
    return1y: 46.8,
    return3y: 168.4,
    aum: 18_650_000_000,
    investorCount: 548_200,
    managementFee: 0.32,
    riskLevel: 1,
    sharpeRatio: 2.85,
    volatility: 1.8,
    maxDrawdown: -0.2,
    composition: [
      { label: "Repo", weight: 48.5 },
      { label: "Mevduat", weight: 32.8 },
      { label: "Bono", weight: 14.2 },
      { label: "Nakit", weight: 4.5 },
    ],
    strategyFit: { conservative: 98, balanced: 55, growth: 15, aggressive: 5 },
  },
  {
    code: "AKP",
    name: "Ak Portföy Para Piyasası Fonu",
    manager: "Ak Portföy",
    type: "Para Piyasası",
    price: 1.032,
    returnDaily: 0.13,
    returnWeekly: 0.70,
    returnMonthly: 3.38,
    returnYtd: 15.8,
    return1y: 45.2,
    return3y: 162.8,
    aum: 14_280_000_000,
    investorCount: 385_600,
    managementFee: 0.35,
    riskLevel: 1,
    sharpeRatio: 2.78,
    volatility: 1.6,
    maxDrawdown: -0.1,
    composition: [
      { label: "Repo", weight: 52.4 },
      { label: "Mevduat", weight: 28.6 },
      { label: "Bono", weight: 15.8 },
      { label: "Nakit", weight: 3.2 },
    ],
    strategyFit: { conservative: 96, balanced: 52, growth: 12, aggressive: 4 },
  },

  // ── Katılım Fonları ──
  {
    code: "ZKH",
    name: "Ziraat Portföy Katılım Hisse Senedi Fonu",
    manager: "Ziraat Portföy",
    type: "Katılım",
    price: 2.742,
    returnDaily: 0.82,
    returnWeekly: 2.15,
    returnMonthly: 4.56,
    returnYtd: 16.8,
    return1y: 38.4,
    return3y: 168.2,
    aum: 6_840_000_000,
    investorCount: 218_600,
    managementFee: 1.28,
    riskLevel: 5,
    sharpeRatio: 1.14,
    volatility: 24.8,
    maxDrawdown: -16.8,
    composition: [
      { label: "Hisse Senedi (Katılım)", weight: 94.6 },
      { label: "Nakit", weight: 5.4 },
    ],
    topHoldings: [
      { ticker: "BIMAS", weight: 9.2 },
      { ticker: "TOASO", weight: 7.8 },
      { ticker: "ASELS", weight: 6.5 },
      { ticker: "MGROS", weight: 5.4 },
      { ticker: "KORDS", weight: 4.8 },
    ],
    strategyFit: { conservative: 14, balanced: 42, growth: 72, aggressive: 82 },
  },
  {
    code: "BKA",
    name: "Bizim Portföy Katılım Altın Fonu",
    manager: "Bizim Portföy",
    type: "Katılım",
    price: 4.286,
    returnDaily: 0.38,
    returnWeekly: 1.64,
    returnMonthly: 3.92,
    returnYtd: 22.4,
    return1y: 48.6,
    return3y: 228.4,
    aum: 3_560_000_000,
    investorCount: 145_800,
    managementFee: 0.92,
    riskLevel: 4,
    sharpeRatio: 1.42,
    volatility: 17.6,
    maxDrawdown: -11.8,
    composition: [
      { label: "Altın (Katılım)", weight: 91.4 },
      { label: "Kira Sertifikası", weight: 5.8 },
      { label: "Nakit", weight: 2.8 },
    ],
    strategyFit: { conservative: 62, balanced: 58, growth: 42, aggressive: 28 },
  },

  // ── Fon Sepeti Fonları ──
  {
    code: "IFS",
    name: "İş Portföy Fon Sepeti Fonu",
    manager: "İş Portföy",
    type: "Fon Sepeti",
    price: 2.148,
    returnDaily: 0.42,
    returnWeekly: 1.18,
    returnMonthly: 2.86,
    returnYtd: 12.4,
    return1y: 28.6,
    return3y: 108.4,
    aum: 2_680_000_000,
    investorCount: 62_400,
    managementFee: 0.95,
    riskLevel: 3,
    sharpeRatio: 1.35,
    volatility: 12.4,
    maxDrawdown: -7.8,
    composition: [
      { label: "Hisse Fonu", weight: 35.2 },
      { label: "Borçlanma Fonu", weight: 28.6 },
      { label: "Altın Fonu", weight: 18.4 },
      { label: "Para Piyasası Fonu", weight: 12.8 },
      { label: "Nakit", weight: 5.0 },
    ],
    strategyFit: { conservative: 55, balanced: 82, growth: 48, aggressive: 22 },
  },
  {
    code: "AFS",
    name: "Ak Portföy Fon Sepeti Fonu",
    manager: "Ak Portföy",
    type: "Fon Sepeti",
    price: 1.856,
    returnDaily: 0.38,
    returnWeekly: 1.05,
    returnMonthly: 2.68,
    returnYtd: 11.6,
    return1y: 26.2,
    return3y: 98.6,
    aum: 1_980_000_000,
    investorCount: 48_200,
    managementFee: 0.88,
    riskLevel: 3,
    sharpeRatio: 1.28,
    volatility: 11.8,
    maxDrawdown: -7.2,
    composition: [
      { label: "Hisse Fonu", weight: 32.4 },
      { label: "Borçlanma Fonu", weight: 30.8 },
      { label: "Altın Fonu", weight: 16.2 },
      { label: "Para Piyasası Fonu", weight: 15.6 },
      { label: "Nakit", weight: 5.0 },
    ],
    strategyFit: { conservative: 58, balanced: 80, growth: 45, aggressive: 20 },
  },

  // ── Değişken Fonlar ──
  {
    code: "TCD",
    name: "TEB Portföy Değişken Fon",
    manager: "TEB Portföy",
    type: "Değişken",
    price: 3.524,
    returnDaily: 0.62,
    returnWeekly: 1.58,
    returnMonthly: 3.72,
    returnYtd: 15.4,
    return1y: 35.8,
    return3y: 142.6,
    aum: 2_240_000_000,
    investorCount: 54_800,
    managementFee: 1.35,
    riskLevel: 5,
    sharpeRatio: 1.18,
    volatility: 20.4,
    maxDrawdown: -13.2,
    composition: [
      { label: "Hisse Senedi", weight: 48.2 },
      { label: "Devlet Tahvili", weight: 22.4 },
      { label: "Altın", weight: 12.8 },
      { label: "Döviz", weight: 8.6 },
      { label: "Nakit", weight: 8.0 },
    ],
    topHoldings: [
      { ticker: "THYAO", weight: 6.2 },
      { ticker: "GARAN", weight: 4.8 },
      { ticker: "ASELS", weight: 3.5 },
    ],
    strategyFit: { conservative: 28, balanced: 65, growth: 68, aggressive: 55 },
  },
  {
    code: "GSD",
    name: "Garanti Portföy Serbest (Değişken) Fon",
    manager: "Garanti Portföy",
    type: "Değişken",
    price: 4.186,
    returnDaily: 0.55,
    returnWeekly: 1.42,
    returnMonthly: 3.48,
    returnYtd: 16.8,
    return1y: 38.2,
    return3y: 156.4,
    aum: 3_120_000_000,
    investorCount: 42_600,
    managementFee: 1.85,
    riskLevel: 5,
    sharpeRatio: 1.25,
    volatility: 19.2,
    maxDrawdown: -11.6,
    composition: [
      { label: "Hisse Senedi", weight: 38.6 },
      { label: "Borçlanma Araçları", weight: 28.2 },
      { label: "Altın", weight: 15.4 },
      { label: "Döviz", weight: 10.8 },
      { label: "Nakit", weight: 7.0 },
    ],
    topHoldings: [
      { ticker: "SAHOL", weight: 4.2 },
      { ticker: "KCHOL", weight: 3.8 },
      { ticker: "THYAO", weight: 3.5 },
    ],
    strategyFit: { conservative: 32, balanced: 68, growth: 62, aggressive: 48 },
  },
];

export const MOCK_PORTFOLIO_RECOMMENDATIONS: PortfolioRecommendation[] = [
  {
    strategy: "Muhafazakar",
    description:
      "Sermayeyi koruma odaklı, dalgalanmalardan minimum etkilenen, sabit getirili araçlara ağırlık veren portföy. Emeklilik yaklaşanlar ve risk almak istemeyenler için ideal.",
    riskLevel: "Düşük",
    expectedReturn: "%12 - %18 (yıllık)",
    allocations: [
      {
        fundCode: "AKK",
        fundName: "Ak Portföy Kısa Vadeli Borçlanma Araçları Fonu",
        weight: 30,
        reason: "Düşük volatilite ve istikrarlı getiri ile portföyün temelini oluşturur",
      },
      {
        fundCode: "IYB",
        fundName: "İş Portföy Yatırım Amaçlı Borçlanma Araçları Fonu",
        weight: 30,
        reason: "Orta-uzun vadeli tahvillerle getiri potansiyeli artırılır",
      },
      {
        fundCode: "GAL",
        fundName: "Garanti Portföy Altın Fonu",
        weight: 20,
        reason: "Enflasyon koruması ve portföy çeşitlendirmesi sağlar",
      },
      {
        fundCode: "IPL",
        fundName: "İş Portföy Para Piyasası Fonu",
        weight: 15,
        reason: "Günlük likidite ihtiyacı için güvenli liman",
      },
      {
        fundCode: "IKA",
        fundName: "İş Portföy Karma Fon",
        weight: 5,
        reason: "Sınırlı hisse maruziyeti ile ekstra getiri potansiyeli",
      },
    ],
    warnings: [
      "Bu portföy enflasyonun üzerinde getiri sağlamayabilir",
      "Faiz düşüşlerinde borçlanma fonları olumlu etkilenir ancak faiz artışlarında kayıp yaşanabilir",
      "Altın fiyatlarındaki ani düşüşler portföyü olumsuz etkileyebilir",
    ],
  },
  {
    strategy: "Dengeli",
    description:
      "Hisse senedi ve sabit getirili araçlar arasında denge kuran, orta vadeli yatırımcılar için tasarlanmış portföy. Büyüme ve koruma arasında optimal denge hedefler.",
    riskLevel: "Orta",
    expectedReturn: "%18 - %28 (yıllık)",
    allocations: [
      {
        fundCode: "IPB",
        fundName: "İş Portföy Hisse Senedi Fonu",
        weight: 20,
        reason: "Aktif yönetilen hisse fonu ile piyasa üstü getiri hedeflenir",
      },
      {
        fundCode: "TI2",
        fundName: "İş Portföy BIST 30 Endeksi Hisse Senedi Fonu",
        weight: 15,
        reason: "BIST 30 endeksine pasif yatırım ile maliyet avantajı",
      },
      {
        fundCode: "DZB",
        fundName: "Deniz Portföy Uzun Vadeli Borçlanma Araçları Fonu",
        weight: 15,
        reason: "Uzun vadeli tahvillerle portföye istikrar katar",
      },
      {
        fundCode: "AKK",
        fundName: "Ak Portföy Kısa Vadeli Borçlanma Araçları Fonu",
        weight: 15,
        reason: "Kısa vadeli araçlarla likidite ve düşük risk sağlar",
      },
      {
        fundCode: "IAL",
        fundName: "İş Portföy Altın Fonu",
        weight: 15,
        reason: "Altın ile döviz ve enflasyon koruması",
      },
      {
        fundCode: "AKX",
        fundName: "Ak Portföy Karma Fon",
        weight: 10,
        reason: "Karma yapısıyla ek çeşitlendirme sağlar",
      },
      {
        fundCode: "IPL",
        fundName: "İş Portföy Para Piyasası Fonu",
        weight: 10,
        reason: "Acil likidite tamponu",
      },
    ],
    warnings: [
      "Borsa düşüşlerinde %35 hisse payı nedeniyle kısa vadeli kayıplar yaşanabilir",
      "Portföy minimum 2-3 yıl tutulmalıdır",
      "Rebalancing (yeniden dengeleme) çeyrek bazında yapılmalıdır",
    ],
  },
  {
    strategy: "Büyüme",
    description:
      "Hisse senedi ağırlıklı, uzun vadeli sermaye artışı hedefleyen portföy. 5+ yıllık yatırım ufku olan ve kısa vadeli dalgalanmalara dayanıklı yatırımcılar için.",
    riskLevel: "Yüksek",
    expectedReturn: "%25 - %40 (yıllık)",
    allocations: [
      {
        fundCode: "IPB",
        fundName: "İş Portföy Hisse Senedi Fonu",
        weight: 25,
        reason: "Aktif yönetimle alfa üretme potansiyeli yüksek",
      },
      {
        fundCode: "TI2",
        fundName: "İş Portföy BIST 30 Endeksi Hisse Senedi Fonu",
        weight: 15,
        reason: "Likit ve büyük şirketlere endeks bazlı erişim",
      },
      {
        fundCode: "GAH",
        fundName: "Garanti Portföy Hisse Senedi Fonu",
        weight: 15,
        reason: "Farklı yönetici perspektifi ile hisse çeşitlendirmesi",
      },
      {
        fundCode: "DZB",
        fundName: "Deniz Portföy Uzun Vadeli Borçlanma Araçları Fonu",
        weight: 15,
        reason: "Tahvil payı ile portföy volatilitesi düşürülür",
      },
      {
        fundCode: "AKX",
        fundName: "Ak Portföy Karma Fon",
        weight: 10,
        reason: "Esnek varlık dağılımı ile fırsatçı pozisyonlar alır",
      },
      {
        fundCode: "IYB",
        fundName: "İş Portföy Yatırım Amaçlı Borçlanma Araçları Fonu",
        weight: 5,
        reason: "Borçlanma tarafında ek çeşitlendirme",
      },
      {
        fundCode: "GAL",
        fundName: "Garanti Portföy Altın Fonu",
        weight: 10,
        reason: "Altın ile kriz dönemlerinde koruma sağlar",
      },
    ],
    warnings: [
      "Kısa vadede %20-25 değer kaybı yaşanabilir",
      "Minimum 5 yıllık yatırım ufku gerektirir",
      "Borsa kriz dönemlerinde panik satış yapılmamalıdır",
      "Düzenli aylık yatırım (DCA) ile maliyet ortalaması düşürülmeli",
    ],
  },
  {
    strategy: "Agresif",
    description:
      "Maksimum getiri hedefleyen, yüksek volatiliteyi kabul eden, ağırlıklı olarak hisse senedine yatırım yapan portföy. Genç yatırımcılar ve yüksek risk toleransı olanlar için.",
    riskLevel: "Çok Yüksek",
    expectedReturn: "%35 - %55+ (yıllık)",
    allocations: [
      {
        fundCode: "TI2",
        fundName: "İş Portföy BIST 30 Endeksi Hisse Senedi Fonu",
        weight: 25,
        reason: "BIST 30 ile büyük hacimli hisselere düşük maliyetli erişim",
      },
      {
        fundCode: "IPB",
        fundName: "İş Portföy Hisse Senedi Fonu",
        weight: 25,
        reason: "Aktif yönetimle endeks üstü getiri potansiyeli",
      },
      {
        fundCode: "AK2",
        fundName: "Ak Portföy BIST 30 Endeksi Hisse Senedi Fonu",
        weight: 15,
        reason: "Farklı portföy yöneticisi ile yönetim riski dağıtılır",
      },
      {
        fundCode: "ZKH",
        fundName: "Ziraat Portföy Katılım Hisse Senedi Fonu",
        weight: 10,
        reason: "Katılım endeksi ile farklı sektör dağılımı",
      },
      {
        fundCode: "AKX",
        fundName: "Ak Portföy Karma Fon",
        weight: 15,
        reason: "Kısa vadeli taktiksel pozisyonlar için esnek yapı",
      },
      {
        fundCode: "IAL",
        fundName: "İş Portföy Altın Fonu",
        weight: 10,
        reason: "Minimum düzeyde koruma ve çeşitlendirme",
      },
    ],
    warnings: [
      "Bu portföy kısa vadede %30-40 değer kaybı yaşayabilir",
      "Sadece kaybetmeyi göze alabileceğiniz paranızla yatırım yapın",
      "Minimum 7+ yıllık yatırım ufku şiddetle tavsiye edilir",
      "Piyasa çöküşlerinde ek alım fırsatı olarak değerlendirmeli",
      "Bu portföy yatırım tavsiyesi niteliği taşımamaktadır",
    ],
  },
];
